# This file was generated by GoReleaser. DO NOT EDIT.
class Centrifugo < Formula
  desc "Real-time messaging server"
  homepage "https://github.com/centrifugal/centrifugo"
  version "2.7.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/centrifugal/centrifugo/releases/download/v2.7.0/centrifugo_2.7.0_darwin_amd64.tar.gz"
    sha256 "9cb26057bfbc788c33447a7ff8555a208ac120aaacd7b67343396667c49e875f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/centrifugal/centrifugo/releases/download/v2.7.0/centrifugo_2.7.0_linux_amd64.tar.gz"
      sha256 "30662a1df8ea081085e166f631a0b74dce49e99630095291d87b07921100c886"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/centrifugal/centrifugo/releases/download/v2.7.0/centrifugo_2.7.0_linux_armv6.tar.gz"
        sha256 "3d6dc401b063929284274dd663b142f7495ea33e95fd2e04f5060a3695347d45"
      end
    end
  end

  def install
    bin.install "centrifugo"
  end
end
