# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Centrifugo < Formula
  desc "Scalable real-time messaging server in a language-agnostic way"
  homepage "https://github.com/centrifugal/centrifugo"
  version "5.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/centrifugal/centrifugo/releases/download/v5.0.4/centrifugo_5.0.4_darwin_arm64.tar.gz"
      sha256 "4ef0ee9b0b8f6c05bc568d7da2f9e6577718e422a1b9dd29c34a020ed0099285"

      def install
        bin.install "centrifugo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/centrifugal/centrifugo/releases/download/v5.0.4/centrifugo_5.0.4_darwin_amd64.tar.gz"
      sha256 "7f9f258ba620a543b383b52914585a2e4418bb9a38a064e1b5a75f160f289182"

      def install
        bin.install "centrifugo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/centrifugal/centrifugo/releases/download/v5.0.4/centrifugo_5.0.4_linux_amd64.tar.gz"
      sha256 "46bc36b3a5599405e262b3b85ee0f471129fa5d75f6a2e624d5051516220f053"

      def install
        bin.install "centrifugo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/centrifugal/centrifugo/releases/download/v5.0.4/centrifugo_5.0.4_linux_armv6.tar.gz"
      sha256 "f7b76d3947c01b9cc741e313b0e1229b8fc322624815c192f2372d88783c934f"

      def install
        bin.install "centrifugo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrifugal/centrifugo/releases/download/v5.0.4/centrifugo_5.0.4_linux_arm64.tar.gz"
      sha256 "be5c6901bca2a07777b1b7baa3f2fdbc0b3173ae9dc49138ef1e4f620d3bcc2f"

      def install
        bin.install "centrifugo"
      end
    end
  end
end
