# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Centrifugo < Formula
  desc "Scalable real-time messaging server in a language-agnostic way"
  homepage "https://github.com/centrifugal/centrifugo"
  version "6.3.1"

  on_macos do
    on_intel do
      url "https://github.com/centrifugal/centrifugo/releases/download/v6.3.1/centrifugo_6.3.1_darwin_amd64.tar.gz"
      sha256 "19d08dfd10c047df6c9813794341bc84649547ae5ac6735d84a101f855dc0d0e"

      def install
        bin.install "centrifugo"
      end
    end
    on_arm do
      url "https://github.com/centrifugal/centrifugo/releases/download/v6.3.1/centrifugo_6.3.1_darwin_arm64.tar.gz"
      sha256 "55605e41a65b72e677424a88318b3449d5f95d0e9a34a141aae2060cbbca724f"

      def install
        bin.install "centrifugo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/centrifugal/centrifugo/releases/download/v6.3.1/centrifugo_6.3.1_linux_amd64.tar.gz"
        sha256 "c44775cffa51ab2bc72adab9b01eb1244e7ec611e1906904c441ae82b8addd16"

        def install
          bin.install "centrifugo"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/centrifugal/centrifugo/releases/download/v6.3.1/centrifugo_6.3.1_linux_armv6.tar.gz"
        sha256 "c9d6958d47fe0c1c45878258ca506bd85ccf02a645a13991bc56cc4d32f65619"

        def install
          bin.install "centrifugo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/centrifugal/centrifugo/releases/download/v6.3.1/centrifugo_6.3.1_linux_arm64.tar.gz"
        sha256 "19dbd7772a5183b87ac6cfba1f63340fb872802b86903cbc2da1b186daabc9a7"

        def install
          bin.install "centrifugo"
        end
      end
    end
  end
end
